#!/usr/bin/env bash
set -euo pipefail

# INPUT
# Directory for which contains the human-corrected FC files.
fc_dir=${fc_dir:-""}
# Directory which contains the original CSV files generated by Fisheye.
csv_dir=${csv_dir:-"0"}
# Optional directory which contains ARIS files for coverage analysis.
aris_dir=${aris_dir:-""}
beam_width_dir=${beam_width_dir:-"fisheye/beam_widths"}

# OUTPUT
# Directory to save temporary report figures.
report_figures_dir=${report_figures_dir:-"post_correction_analysis/temp_report_figures"}
# File path to save the final PDF report.
report_fp=${report_fp:-"predicted_vs_corrected_report.pdf"}

args=(
  --fc-dir "$fc_dir"
  --csv-dir "$csv_dir"
  --report-figures-dir "$report_figures_dir"
  --report-fp "$report_fp"
  --beam-width-dir "$beam_width_dir"
)

if [[ -n "${aris_dir}" ]]; then
  args+=(--aris-dir "$aris_dir")
fi

python post_correction_analysis/gen_comparison_report.py "${args[@]}"
