[tool.poetry]
name = "fisheye"
version = "v1.0.0-dev.2"
description = "Performing inference on sonar data."
authors = ["Madison Van Horn"]
readme = "README.md"
packages = [{include = "fisheye"}]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
pandas = [
    {version = "<1.5.0", python = "<3.10"},
    { version = "^2.2.3", python = ">=3.10" }
]
pillow = [
    {version = "<10.0.0", python = "<3.10"},
    { version = "^11.1.0", python = ">=3.10" }
]
matplotlib = [
    {version = "<3.7.0", python = "<3.10"},
    { version = "^3.10.0", python = ">=3.10" }
]
tqdm = "^4.67.1"
opencv-python = "<4.7.0"
yolov5 = "^7.0.14"
filterpy = "^1.4.5"
structlog = [
    {version = "<23.0.0", python = "<3.10"},
    { version = "^25.3.0", python = ">=3.10" }
]
tomli = "^2.2.1"
lightning = [
    { version = "<2.1.0", python = "<3.10" },
    { version = "^2.5.0.post0", python = ">=3.10" }
]

[tool.poetry.group.mac.dependencies]
torch = [{version = "^2.6.0", python = ">=3.10" }]
torchvision = [
  { version = "0.22.0", python = ">=3.10" }
]

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[tool.poetry.group.dev.dependencies]
jupyterlab = [
    { version = "<4.0.0", python = "<3.10"},
    { version = "^4.3.5", python = ">=3.10" }
]
ipykernel = [
    { version = "<6.0.0", python = "<3.10"},
    { version = "^6.29.5", python = ">=3.10" }
]
wandb = "^0.19.5"
pre-commit = [
    { version = "<3.0.0", python = "<3.10"},
    { version = "^4.1.0", python = ">=3.10" }
]
black = [
    { version = "<23", python = "<3.10"},
    { version = "^25.1.0", python = ">=3.10" }
]

memory-profiler = "^0.61.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
