import logging
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Callable, Any, Union

import pandas as pd

from fisheye.enums import ExportType
from fisheye.utils import get_unwarped_distance

logger = logging.getLogger(__name__)


def to_detailed_csv(data, out_dir):
    """Export inference results to CSV file.

    A detailed CSV with where each row is considered a count with additional metadata.

    Args:
        data (dict): Dictionary of inference results.
        out_dir (str): Output directory for CSV files.
    """
    out_file = os.path.join(out_dir, datetime.now().strftime("%Y-%m-%d"))
    flattened_data = [item for sublist in data if sublist for item in sublist]
    out_file = out_file + "_" + Path(flattened_data[0].get("file_name")).stem

    if not flattened_data:
        raise ValueError(
            f"No counts were found in the provided data. Nothing to export."
        )

    df = pd.DataFrame(flattened_data)
    df.to_csv(out_file + ".csv", index=False)

    logger.info(f"Exported results to {out_dir}")


def to_summary_csv(data, out_dir):
    """Export inference results to CSV file.

    A summary CSV containing counts for each ARIS/DDF file to a single CSV

    Args:
        data (dict): Dictionary of inference results.
        out_dir (str): Output directory for CSV files.
    """
    out_file = os.path.join(out_dir, datetime.now().strftime("%Y-%m-%d"))
    flattened_data = [item for sublist in data if sublist for item in sublist]

    if not flattened_data:
        raise ValueError(
            f"No counts were found in the provided data. Nothing to export."
        )

    df = pd.DataFrame(flattened_data)
    # Save off all track counts to CSV
    df.drop(columns=["bbox", "metadata"], inplace=True)

    direction_counts = (
        df.groupby(["file_name", "fish_id", "direction"]).size().unstack(fill_value=0)
    )

    # Calculate the absolute left and right counts for each fish_id within each file
    direction_counts["absolute_left"] = (
        direction_counts["left"] > direction_counts["right"]
    ).astype(int)

    direction_counts["absolute_right"] = (
        direction_counts["right"] > direction_counts["left"]
    ).astype(int)

    # Aggregate over fish_id to calculate the total absolute_left and absolute_right per file_name
    file_counts = direction_counts.groupby("file_name")[
        ["absolute_left", "absolute_right"]
    ].sum()

    file_counts["net_count"] = abs(
        file_counts["absolute_left"] - file_counts["absolute_right"]
    )

    final_result = file_counts.reset_index()
    # Save absolute left, right, and net counts for each ARIS/DDF file to a single CSV
    final_result.to_csv(out_file + "_summary.csv", index=False)

    logger.info(f"Exported summary to {out_dir}")


def to_txt(data, out_dir):
    """Export inference results to TXT file.

    This exporter replicates the format of the TXT output generated by the ARISFish software from Sound Metrics.
    Args:
        data (dict): Dictionary of inference results.
        out_dir (str): Output directory for TXT file(s).
    """
    flattened_data = [item for sublist in data if sublist for item in sublist]
    if not flattened_data:
        raise ValueError(
            f"No tracks were found in the provided data. Nothing to export."
        )
    df = pd.DataFrame(flattened_data)
    # Calculate the distance from the sonar camera to the fish in an unwarped frame
    df["distance"] = df.apply(get_unwarped_distance, axis=1)

    title = "*** Manual Marking (Manual Sizing: Q = Quality, N = Repeat Count) ***"

    # Add any new header fields to the end of the list (must maintain current order)
    # Also make sure to add any new header fields to `row_data`
    headers = [
        "File",
        "Total",
        "Frame#",
        "Dir",
        "R (m)",
        "Theta",
        "L(cm)",
        "dR(cm)",
        "L/dR",
        "Aspect",
        "Time",
        "Date",
        "Latitude",
        "Longitude",
        "Pan",
        "Tilt",
        "Roll",
        "Species",
        "Motion",
        "Q",
        "N",
        "Comment",
    ]

    col_width = 2
    header_line = "  ".join(f"{h:<{col_width}}" for h in headers)
    separator_line = "-" * len(header_line)

    for file_name, group_df in df.groupby("file_name"):
        match = re.search(r"(\d{4}-\d{2}-\d{2})", file_name)
        # Attempt to get date from filename
        date = match.group(1) if match else datetime.now().strftime("%Y-%m-%d")
        group_df_sorted = group_df.sort_values(by="frame_id")

        row_data = {
            "File": 1,
            "Total": 0,
            "Frame#": 0,
            "Dir": "",
            "R (m)": 0.0,
            "Theta": 0.0,  # TODO (MVH) - update to use our theta estimations
            "L(cm)": 0.0,  # TODO (MVH) - update to use our length estimations
            "dR(cm)": 0.0,
            "L/dR": 0.0,
            "Aspect": 0.0,
            "Time": "00:00:00",
            "Date": date,
            "Latitude": "N 00 d  0.00000 m",
            "Longitude": "E 000 d  0.00000 m",
            "Pan": 0.0,
            "Tilt": 0.0,
            "Roll": 0.0,
            "Species": "Unknown",
            "Motion": "Running <->",
            "Q": 5,
            "N": 1,
            "Comment": "",
        }

        file_stem = Path(file_name).stem
        out_file = os.path.join(out_dir, f"FCe_{file_stem}_ID_.txt")

        with open(out_file, "w") as f:
            f.write(title + "\n\n")
            f.write(header_line + "\n")
            f.write(separator_line + "\n")

            for i, (_, row) in enumerate(group_df_sorted.iterrows()):
                # Merge row with defaults to ensure all keys are present
                row_data["Total"] = row_data["Total"] + 1
                row_data["Frame#"] = row["frame_id"]
                # Left to right is considered upstream for now
                row_data["Dir"] = "Up" if row["direction"] == "left" else "Down"
                row_data["R (m)"] = row["distance"]
                row_line = "  ".join(f"{str(row_data[h]):<10}" for h in headers)
                f.write(row_line + "\n")

        print(f"Exported results to {out_file}")


def to_mot(data, output_dir, filename):
    """Export inference results to MOT file(s). Expects data to be in MOT output already."""
    out_path = os.path.join(output_dir, filename + ".txt")

    mot_lines = []
    for row in data:
        # Convert frame number to int (if needed) and format row to MOT string
        frame = int(row["frame"])
        mot_line = "{},{},{:.3f},{:.3f},{:.3f},{:.3f},{:.3f}".format(
            frame,
            row["id"],
            row["bb_left"],
            row["bb_top"],
            row["bb_width"],
            row["bb_height"],
            row["conf"],
        )
        mot_lines.append(mot_line)

    with open(out_path, "w") as f:
        f.write("\n".join(mot_lines))


# Add any new export functions here
EXPORT_FUNCTIONS: Dict[ExportType, Callable[[Any, str], None]] = {
    ExportType.DETAILED_CSV: to_detailed_csv,
    ExportType.SUMMARY_CSV: to_summary_csv,
    ExportType.TXT: to_txt,
    ExportType.MOT: to_mot,
}


def get_exporter(export_type: ExportType | str) -> Callable[[Any, str], None]:
    """Retrieve the appropriate export function."""

    if isinstance(export_type, str):
        export_type = ExportType(export_type)

    return EXPORT_FUNCTIONS.get(export_type)


def save_to_disk(
    results, output_dir, export_types: Union[list[ExportType], ExportType]
) -> None:
    """Save results to disk."""
    if not isinstance(export_types, list):
        export_types = [export_types]

    for export_option in export_types:
        exporter = get_exporter(export_option)
        exporter(results, output_dir)
