import logging
import os
from datetime import datetime
from typing import Dict, Callable, Any

import pandas as pd

from fisheye.enums import ExportType


logger = logging.getLogger(__name__)


def to_csv(data, out_dir):
    """Export inference results to CSV file.

    Two CSVs are generated:
    1. A detailed CSV with all track counts.
    2. A summary CSV with net counts per ARIS/DDF file.
    """
    out_file = os.path.join(out_dir, datetime.now().strftime("%Y-%m-%d_%H-%M-%S"))
    flattened_data = [item for sublist in data if sublist for item in sublist]
    if not flattened_data:
        raise ValueError(
            f"No counts were found in the provided data. Nothing to export."
        )

    df = pd.DataFrame(flattened_data)
    # Save off all track counts to CSV
    df.to_csv(out_file + ".csv", index=False)

    direction_counts = (
        df.groupby(["file_name", "fish_id", "direction"]).size().unstack(fill_value=0)
    )

    # Calculate the absolute left and right counts for each fish_id within each file
    direction_counts["absolute_left"] = (
        direction_counts["left"] > direction_counts["right"]
    ).astype(int)
    direction_counts["absolute_right"] = (
        direction_counts["right"] > direction_counts["left"]
    ).astype(int)

    # Aggregate over fish_id to calculate the total absolute_left and absolute_right per file_name
    file_counts = direction_counts.groupby("file_name")[
        ["absolute_left", "absolute_right"]
    ].sum()

    file_counts["net_count"] = abs(
        file_counts["absolute_left"] - file_counts["absolute_right"]
    )

    final_result = file_counts.reset_index()
    # Save off the absolute left counts, absolute right counts, absolute net counts for each ARIS/DDF file to CSV
    final_result.to_csv(out_file + "_summary.csv", index=False)

    logger.info(f"Exported results to {out_dir}")


def to_txt(data, out_dir):
    """Export inference results to TXT file.

    This exporter replicates the format of the TXT output generated by the ARISFish software from SoundMetrics.
    """
    pass


# Add any new export functions here
EXPORT_FUNCTIONS: Dict[ExportType, Callable[[Any, str], None]] = {
    ExportType.CSV: to_csv,
    ExportType.TXT: to_txt,
}


def get_exporter(export_type: ExportType | str) -> Callable[[Any, str], None]:
    """Retrieve the appropriate export function."""

    if isinstance(export_type, str):
        export_type = ExportType(export_type)

    return EXPORT_FUNCTIONS.get(export_type)
