import os
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Callable, Any, Union, List

import pandas as pd
import structlog

from fisheye.enums import ExportType
from fisheye.utils import (
    get_unwarped_distance,
    get_theta,
)

logger = structlog.get_logger()


def to_detailed_csv(data, out_dir, job_id: str = None):
    """Export inference results to CSV file.

    A detailed CSV with where each row is considered a count with additional metadata.

    Args:
        data (dict): Dictionary of inference results.
        out_dir (str): Output directory for CSV files.
        job_id (str): Job ID.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d")
    job_suffix = f"_{job_id}" if job_id else ""
    out_file = os.path.join(out_dir, f"{timestamp}{job_suffix}")

    flattened_data = [item for sublist in data if sublist for item in sublist]

    if not flattened_data:
        logger.warning(f"No counts were found in the provided data. Nothing to export.")
        return

    out_file = out_file + "_" + Path(flattened_data[0].get("file_name")).stem + ".csv"

    df = pd.DataFrame(flattened_data)
    df.to_csv(out_file, index=False)

    logger.info(f"exported_results", output_dir=out_file)


def to_summary_csv(data, out_dir, job_id: str = None):
    """Export inference results to CSV file, ensuring all files are represented.

    Args:
        data (dict): Dictionary of inference results.
        out_dir (str): Output directory for CSV files.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d")
    job_suffix = f"_{job_id}" if job_id else ""
    out_file = os.path.join(out_dir, f"{timestamp}{job_suffix}_summary.csv")

    flattened_data = [item for sublist in data if sublist for item in sublist]

    if not flattened_data:
        logger.warning("No counts were found in the provided data. Nothing to export.")
        return

    df = pd.DataFrame(flattened_data)
    df["fish_id"] = df.get("fish_id", pd.NA)
    df["direction"] = df.get("direction", pd.NA)

    # Get all unique file names upfront
    all_files = df["file_name"].unique()

    # Only valid rows for counting
    valid_rows = df.dropna(subset=["fish_id", "direction"])

    if not valid_rows.empty:
        direction_counts = (
            valid_rows.groupby(["file_name", "fish_id", "direction"])
            .size()
            .unstack(fill_value=0)
        )

        direction_counts = direction_counts.reindex(
            columns=["left", "right"], fill_value=0
        )

        direction_counts["absolute_left"] = (
            direction_counts["left"] > direction_counts["right"]
        ).astype(int)
        direction_counts["absolute_right"] = (
            direction_counts["right"] > direction_counts["left"]
        ).astype(int)

        file_counts = direction_counts.groupby("file_name")[
            ["absolute_left", "absolute_right"]
        ].sum()

    else:
        file_counts = pd.DataFrame(
            columns=["absolute_left", "absolute_right"], index=all_files
        ).fillna(0)

    # Ensure all files are represented
    for file in all_files:
        if file not in file_counts.index:
            file_counts.loc[file] = {"absolute_left": 0, "absolute_right": 0}

    file_counts["net_count"] = (
        file_counts["absolute_left"] - file_counts["absolute_right"]
    )
    final_result = file_counts.reset_index().rename(columns={"index": "file_name"})

    final_result.to_csv(out_file, index=False)

    logger.info(f"exported_summary", output_dir=out_file)


def to_txt(data, out_dir):
    """Export inference results to TXT file.

    This exporter replicates the format of the TXT output generated by the ARISFish software from Sound Metrics.
    Args:
        data (dict): Dictionary of inference results.
        out_dir (str): Output directory for TXT file(s).
    """
    flattened_data = [item for sublist in data if sublist for item in sublist]
    if not flattened_data:
        logger.warning(f"No counts were found in the provided data. Nothing to export.")
        return

    df = pd.DataFrame(flattened_data)

    if not df["bbox"].isna().all():
        # Calculate the distance from the sonar camera to the fish in an unwarped frame
        df["distance"] = df.apply(get_unwarped_distance, axis=1)
        df["theta"] = df.apply(get_theta, axis=1)

    title = "*** Manual Marking (Manual Sizing: Q = Quality, N = Repeat Count) ***"

    # Add any new header fields to the end of the list (must maintain current order)
    # Also make sure to add any new header fields to `row_data`
    headers = [
        "File",
        "Total",
        "Frame#",
        "Dir",
        "R (m)",
        "Theta",
        "L(cm)",
        "dR(cm)",
        "L/dR",
        "Aspect",
        "Time",
        "Date",
        "Latitude",
        "Longitude",
        "Pan",
        "Tilt",
        "Roll",
        "Species",
        "Motion",
        "Q",
        "N",
        "Comment",
    ]

    col_width = 10
    header_line = "".join(f"{h:<{col_width}}" for h in headers)
    separator_line = "-" * len(header_line)

    for file_name, group_df in df.groupby("file_name"):
        match = re.search(r"(\d{4}-\d{2}-\d{2})", file_name)
        # Attempt to get date from filename
        date = match.group(1) if match else datetime.now().strftime("%Y-%m-%d")
        group_df_sorted = group_df.sort_values(by="frame_id")

        row_data = {
            "File": 1,
            "Total": 0,
            "Frame#": 0,
            "Dir": "",
            "R (m)": 0.0,
            "Theta": 0.0,  # TODO (MVH) - update to use our theta estimations
            "L(cm)": 0.0,  # TODO (MVH) - update to use our length estimations
            "dR(cm)": 0.0,
            "L/dR": 0.0,
            "Aspect": 0.0,
            "Time": "00:00:00",
            "Date": date,
            "Latitude": "N 00 d  0.00000 m",
            "Longitude": "E 000 d  0.00000 m",
            "Pan": 0.0,
            "Tilt": 0.0,
            "Roll": 0.0,
            "Species": "Unknown",
            "Motion": "Running <->",
            "Q": 5,
            "N": 1,
            "Comment": 1,
        }

        file_stem = Path(file_name).stem
        out_file = os.path.join(out_dir, f"FCe_{file_stem}_ID_.txt")

        with open(out_file, "w") as f:
            f.write(title + "\n\n")
            f.write(header_line + "\n")
            f.write(separator_line + "\n")

            for _, row in group_df_sorted.iterrows():
                bbox = row.get("bbox")
                has_data = (
                    bbox is not None
                    and len(bbox) > 0
                    and "distance" in row
                    and pd.notna(row["distance"])
                )

                if has_data:
                    row_data = {
                        "File": 1,
                        "Total": row_data["Total"] + 1,
                        "Frame#": row["frame_id"],
                        "Dir": "Up" if row.get("direction") == "left" else "Down",
                        "R (m)": row["distance"],
                        "Theta": row["theta"],
                        "L(cm)": 0.0,
                        "dR(cm)": 0.0,
                        "L/dR": 0.0,
                        "Aspect": 0.0,
                        "Time": "00:00:00",
                        "Date": date,
                        "Latitude": "N 00 d  0.00000 m",
                        "Longitude": "E 000 d  0.00000 m",
                        "Pan": 0.0,
                        "Tilt": 0.0,
                        "Roll": 0.0,
                        "Species": "Unknown",
                        "Motion": "Running <->",
                        "Q": 5,
                        "N": 1,
                        "Comment": f"Centerlinecrossingtrackid{row['fish_id']}",
                    }

                    row_line = "".join(f"{str(row_data[h]):<10}" for h in headers)
                else:
                    row_line = "".join(["" for _ in headers])

                f.write(row_line + "\n")

        logger.info(f"exported_txt", output_dir=out_file)


def to_mot(data, output_dir, filename):
    """Export inference results to MOT file(s). Expects data to be in MOT output already."""
    out_path = os.path.join(output_dir, filename + ".txt")

    mot_lines = []
    for row in data:
        # Convert frame number to int (if needed) and format row to MOT string
        frame = int(row["frame"])
        mot_line = "{},{},{:.3f},{:.3f},{:.3f},{:.3f},{:.3f}".format(
            frame,
            row["id"],
            row["bb_left"],
            row["bb_top"],
            row["bb_width"],
            row["bb_height"],
            row["conf"],
        )
        mot_lines.append(mot_line)

    with open(out_path, "w") as f:
        f.write("\n".join(mot_lines))

    logger.info(f"exported_mot", output_dir=out_path)


# Add any new export functions here
EXPORT_FUNCTIONS: Dict[ExportType, Callable[[Any, str], None]] = {
    ExportType.DETAILED_CSV: to_detailed_csv,
    ExportType.SUMMARY_CSV: to_summary_csv,
    ExportType.TXT: to_txt,
    ExportType.MOT: to_mot,
}


def get_exporter(export_type: Union[ExportType, str]) -> Callable[[Any, str], None]:
    """Retrieve the appropriate export function."""

    if isinstance(export_type, str):
        export_type = ExportType(export_type)

    return EXPORT_FUNCTIONS.get(export_type)


def save_to_disk(
    results, output_dir, export_types: Union[List[ExportType], ExportType], job_id: str
) -> None:
    """Save results to disk."""
    if not results or all(len(sublist) == 0 for sublist in results):
        logger.warning(f"No counts were found in the provided data. Nothing to export.")
        return

    if not isinstance(export_types, list):
        export_types = [export_types]

    for export_option in export_types:
        exporter = get_exporter(export_option)

        if export_option in [ExportType.DETAILED_CSV, ExportType.SUMMARY_CSV]:
            exporter(results, output_dir, job_id=job_id)

        else:
            exporter(results, output_dir)
