import os
from pathlib import Path

import pytest

ARIS_FILE = os.path.join(os.path.dirname(__file__), "data", "sample.aris")
DDF_FILE = os.path.join(os.path.dirname(__file__), "data", "sample.ddf")
CORRUPTED_FILE = os.path.join(os.path.dirname(__file__), "data", "corrupted.aris")
SHORTENED_DDF_FILE = os.path.join(
    os.path.dirname(__file__), "data", "shortened_clip.ddf"
)
INVALID_FRAME_INDICES = os.path.join(
    os.path.dirname(__file__), "data", "invalid_frame_indices.aris"
)


@pytest.fixture(scope="session")
def beam_widths_path():
    """Fixture to get the path to the beam_widths directory."""
    project_root = Path(__file__).parent.parent  # Get the root of the fisheye/ project
    beam_widths_dir = (
        project_root / "fisheye" / "beam_widths"
    )  # Navigate to beam_widths
    return beam_widths_dir


@pytest.fixture
def tracks_crossing_left_to_right():
    """Fixture for sample track data crossing from left-to-right."""

    return [
        {
            "frame": 48,
            "id": 2,
            "x_center": 0.201,
            "y_center": 0.432,
            "width": 0.028,
            "height": 0.008,
            "conf": 0.444,
        },
        {
            "frame": 49,
            "id": 2,
            "x_center": 0.202,
            "y_center": 0.432,
            "width": 0.032,
            "height": 0.008,
            "conf": 0.548,
        },
        {
            "frame": 50,
            "id": 2,
            "x_center": 0.201,
            "y_center": 0.432,
            "width": 0.035,
            "height": 0.009,
            "conf": 0.611,
        },
        {
            "frame": 51,
            "id": 2,
            "x_center": 0.199,
            "y_center": 0.43,
            "width": 0.042,
            "height": 0.011,
            "conf": 0.566,
        },
        {
            "frame": 52,
            "id": 2,
            "x_center": 0.201,
            "y_center": 0.43,
            "width": 0.048,
            "height": 0.012,
            "conf": 0.516,
        },
        {
            "frame": 53,
            "id": 2,
            "x_center": 0.203,
            "y_center": 0.43,
            "width": 0.051,
            "height": 0.014,
            "conf": 0.321,
        },
        {
            "frame": 54,
            "id": 2,
            "x_center": 0.206,
            "y_center": 0.43,
            "width": 0.053,
            "height": 0.014,
            "conf": 0.217,
        },
        {
            "frame": 55,
            "id": 2,
            "x_center": 0.203,
            "y_center": 0.428,
            "width": 0.057,
            "height": 0.015,
            "conf": 0.313,
        },
        {
            "frame": 56,
            "id": 2,
            "x_center": 0.219,
            "y_center": 0.432,
            "width": 0.062,
            "height": 0.016,
            "conf": 0.195,
        },
        {
            "frame": 57,
            "id": 2,
            "x_center": 0.235,
            "y_center": 0.434,
            "width": 0.06,
            "height": 0.014,
            "conf": 0.312,
        },
        {
            "frame": 60,
            "id": 2,
            "x_center": 0.256,
            "y_center": 0.438,
            "width": 0.059,
            "height": 0.013,
            "conf": 0.46,
        },
        {
            "frame": 61,
            "id": 2,
            "x_center": 0.263,
            "y_center": 0.439,
            "width": 0.056,
            "height": 0.012,
            "conf": 0.367,
        },
        {
            "frame": 62,
            "id": 2,
            "x_center": 0.266,
            "y_center": 0.437,
            "width": 0.059,
            "height": 0.014,
            "conf": 0.406,
        },
        {
            "frame": 63,
            "id": 2,
            "x_center": 0.276,
            "y_center": 0.439,
            "width": 0.057,
            "height": 0.013,
            "conf": 0.307,
        },
        {
            "frame": 64,
            "id": 2,
            "x_center": 0.29,
            "y_center": 0.442,
            "width": 0.059,
            "height": 0.011,
            "conf": 0.575,
        },
        {
            "frame": 65,
            "id": 2,
            "x_center": 0.295,
            "y_center": 0.443,
            "width": 0.058,
            "height": 0.011,
            "conf": 0.507,
        },
        {
            "frame": 66,
            "id": 2,
            "x_center": 0.299,
            "y_center": 0.443,
            "width": 0.059,
            "height": 0.01,
            "conf": 0.623,
        },
        {
            "frame": 67,
            "id": 2,
            "x_center": 0.302,
            "y_center": 0.443,
            "width": 0.06,
            "height": 0.01,
            "conf": 0.558,
        },
        {
            "frame": 68,
            "id": 2,
            "x_center": 0.309,
            "y_center": 0.443,
            "width": 0.062,
            "height": 0.009,
            "conf": 0.613,
        },
        {
            "frame": 69,
            "id": 2,
            "x_center": 0.313,
            "y_center": 0.443,
            "width": 0.065,
            "height": 0.009,
            "conf": 0.555,
        },
        {
            "frame": 70,
            "id": 2,
            "x_center": 0.315,
            "y_center": 0.443,
            "width": 0.069,
            "height": 0.01,
            "conf": 0.636,
        },
        {
            "frame": 71,
            "id": 2,
            "x_center": 0.315,
            "y_center": 0.442,
            "width": 0.075,
            "height": 0.01,
            "conf": 0.591,
        },
        {
            "frame": 72,
            "id": 2,
            "x_center": 0.322,
            "y_center": 0.442,
            "width": 0.077,
            "height": 0.01,
            "conf": 0.6,
        },
        {
            "frame": 73,
            "id": 2,
            "x_center": 0.325,
            "y_center": 0.442,
            "width": 0.081,
            "height": 0.01,
            "conf": 0.673,
        },
        {
            "frame": 74,
            "id": 2,
            "x_center": 0.346,
            "y_center": 0.443,
            "width": 0.078,
            "height": 0.01,
            "conf": 0.499,
        },
        {
            "frame": 75,
            "id": 2,
            "x_center": 0.347,
            "y_center": 0.442,
            "width": 0.081,
            "height": 0.01,
            "conf": 0.65,
        },
        {
            "frame": 76,
            "id": 2,
            "x_center": 0.357,
            "y_center": 0.441,
            "width": 0.079,
            "height": 0.01,
            "conf": 0.569,
        },
        {
            "frame": 77,
            "id": 2,
            "x_center": 0.362,
            "y_center": 0.441,
            "width": 0.08,
            "height": 0.01,
            "conf": 0.507,
        },
        {
            "frame": 78,
            "id": 2,
            "x_center": 0.376,
            "y_center": 0.442,
            "width": 0.074,
            "height": 0.009,
            "conf": 0.616,
        },
        {
            "frame": 79,
            "id": 2,
            "x_center": 0.383,
            "y_center": 0.441,
            "width": 0.074,
            "height": 0.009,
            "conf": 0.623,
        },
        {
            "frame": 80,
            "id": 2,
            "x_center": 0.39,
            "y_center": 0.441,
            "width": 0.077,
            "height": 0.009,
            "conf": 0.643,
        },
        {
            "frame": 81,
            "id": 2,
            "x_center": 0.394,
            "y_center": 0.44,
            "width": 0.078,
            "height": 0.009,
            "conf": 0.631,
        },
        {
            "frame": 82,
            "id": 2,
            "x_center": 0.4,
            "y_center": 0.44,
            "width": 0.08,
            "height": 0.009,
            "conf": 0.656,
        },
        {
            "frame": 83,
            "id": 2,
            "x_center": 0.408,
            "y_center": 0.44,
            "width": 0.081,
            "height": 0.009,
            "conf": 0.647,
        },
        {
            "frame": 84,
            "id": 2,
            "x_center": 0.414,
            "y_center": 0.439,
            "width": 0.085,
            "height": 0.01,
            "conf": 0.686,
        },
        {
            "frame": 85,
            "id": 2,
            "x_center": 0.422,
            "y_center": 0.438,
            "width": 0.086,
            "height": 0.01,
            "conf": 0.689,
        },
        {
            "frame": 86,
            "id": 2,
            "x_center": 0.442,
            "y_center": 0.438,
            "width": 0.084,
            "height": 0.01,
            "conf": 0.596,
        },
        {
            "frame": 87,
            "id": 2,
            "x_center": 0.45,
            "y_center": 0.438,
            "width": 0.083,
            "height": 0.01,
            "conf": 0.628,
        },
        {
            "frame": 88,
            "id": 2,
            "x_center": 0.457,
            "y_center": 0.437,
            "width": 0.08,
            "height": 0.009,
            "conf": 0.65,
        },
        {
            "frame": 89,
            "id": 2,
            "x_center": 0.467,
            "y_center": 0.437,
            "width": 0.079,
            "height": 0.009,
            "conf": 0.683,
        },
        {
            "frame": 90,
            "id": 2,
            "x_center": 0.478,
            "y_center": 0.437,
            "width": 0.078,
            "height": 0.009,
            "conf": 0.704,
        },
        {
            "frame": 91,
            "id": 2,
            "x_center": 0.485,
            "y_center": 0.437,
            "width": 0.079,
            "height": 0.01,
            "conf": 0.715,
        },
        {
            "frame": 92,
            "id": 2,
            "x_center": 0.493,
            "y_center": 0.436,
            "width": 0.08,
            "height": 0.01,
            "conf": 0.701,
        },
        {
            "frame": 93,
            "id": 2,
            "x_center": 0.503,
            "y_center": 0.436,
            "width": 0.08,
            "height": 0.01,
            "conf": 0.711,
        },
        {
            "frame": 94,
            "id": 2,
            "x_center": 0.519,
            "y_center": 0.436,
            "width": 0.081,
            "height": 0.01,
            "conf": 0.62,
        },
        {
            "frame": 95,
            "id": 2,
            "x_center": 0.527,
            "y_center": 0.436,
            "width": 0.078,
            "height": 0.01,
            "conf": 0.618,
        },
        {
            "frame": 96,
            "id": 2,
            "x_center": 0.539,
            "y_center": 0.436,
            "width": 0.079,
            "height": 0.01,
            "conf": 0.624,
        },
        {
            "frame": 97,
            "id": 2,
            "x_center": 0.548,
            "y_center": 0.436,
            "width": 0.077,
            "height": 0.009,
            "conf": 0.582,
        },
        {
            "frame": 98,
            "id": 2,
            "x_center": 0.551,
            "y_center": 0.436,
            "width": 0.077,
            "height": 0.009,
            "conf": 0.591,
        },
        {
            "frame": 99,
            "id": 2,
            "x_center": 0.557,
            "y_center": 0.435,
            "width": 0.078,
            "height": 0.009,
            "conf": 0.445,
        },
        {
            "frame": 100,
            "id": 2,
            "x_center": 0.565,
            "y_center": 0.435,
            "width": 0.076,
            "height": 0.01,
            "conf": 0.532,
        },
        {
            "frame": 101,
            "id": 2,
            "x_center": 0.578,
            "y_center": 0.435,
            "width": 0.076,
            "height": 0.01,
            "conf": 0.566,
        },
        {
            "frame": 102,
            "id": 2,
            "x_center": 0.589,
            "y_center": 0.434,
            "width": 0.079,
            "height": 0.01,
            "conf": 0.61,
        },
        {
            "frame": 103,
            "id": 2,
            "x_center": 0.597,
            "y_center": 0.434,
            "width": 0.081,
            "height": 0.01,
            "conf": 0.638,
        },
        {
            "frame": 104,
            "id": 2,
            "x_center": 0.605,
            "y_center": 0.434,
            "width": 0.08,
            "height": 0.01,
            "conf": 0.572,
        },
        {
            "frame": 105,
            "id": 2,
            "x_center": 0.611,
            "y_center": 0.434,
            "width": 0.082,
            "height": 0.01,
            "conf": 0.556,
        },
        {
            "frame": 106,
            "id": 2,
            "x_center": 0.616,
            "y_center": 0.434,
            "width": 0.082,
            "height": 0.01,
            "conf": 0.551,
        },
        {
            "frame": 107,
            "id": 2,
            "x_center": 0.632,
            "y_center": 0.434,
            "width": 0.079,
            "height": 0.01,
            "conf": 0.57,
        },
        {
            "frame": 108,
            "id": 2,
            "x_center": 0.639,
            "y_center": 0.434,
            "width": 0.078,
            "height": 0.01,
            "conf": 0.517,
        },
        {
            "frame": 109,
            "id": 2,
            "x_center": 0.649,
            "y_center": 0.434,
            "width": 0.078,
            "height": 0.01,
            "conf": 0.633,
        },
        {
            "frame": 110,
            "id": 2,
            "x_center": 0.656,
            "y_center": 0.434,
            "width": 0.077,
            "height": 0.01,
            "conf": 0.633,
        },
        {
            "frame": 111,
            "id": 2,
            "x_center": 0.658,
            "y_center": 0.433,
            "width": 0.077,
            "height": 0.01,
            "conf": 0.63,
        },
        {
            "frame": 112,
            "id": 2,
            "x_center": 0.661,
            "y_center": 0.433,
            "width": 0.075,
            "height": 0.01,
            "conf": 0.514,
        },
        {
            "frame": 113,
            "id": 2,
            "x_center": 0.676,
            "y_center": 0.433,
            "width": 0.073,
            "height": 0.01,
            "conf": 0.482,
        },
        {
            "frame": 114,
            "id": 2,
            "x_center": 0.686,
            "y_center": 0.433,
            "width": 0.073,
            "height": 0.01,
            "conf": 0.27,
        },
        {
            "frame": 115,
            "id": 2,
            "x_center": 0.699,
            "y_center": 0.434,
            "width": 0.074,
            "height": 0.01,
            "conf": 0.434,
        },
        {
            "frame": 116,
            "id": 2,
            "x_center": 0.706,
            "y_center": 0.433,
            "width": 0.074,
            "height": 0.01,
            "conf": 0.434,
        },
        {
            "frame": 117,
            "id": 2,
            "x_center": 0.719,
            "y_center": 0.433,
            "width": 0.073,
            "height": 0.01,
            "conf": 0.515,
        },
        {
            "frame": 118,
            "id": 2,
            "x_center": 0.728,
            "y_center": 0.433,
            "width": 0.07,
            "height": 0.01,
            "conf": 0.591,
        },
        {
            "frame": 119,
            "id": 2,
            "x_center": 0.732,
            "y_center": 0.432,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.659,
        },
        {
            "frame": 120,
            "id": 2,
            "x_center": 0.735,
            "y_center": 0.431,
            "width": 0.064,
            "height": 0.01,
            "conf": 0.677,
        },
        {
            "frame": 121,
            "id": 2,
            "x_center": 0.738,
            "y_center": 0.43,
            "width": 0.062,
            "height": 0.01,
            "conf": 0.686,
        },
        {
            "frame": 122,
            "id": 2,
            "x_center": 0.742,
            "y_center": 0.43,
            "width": 0.059,
            "height": 0.01,
            "conf": 0.616,
        },
        {
            "frame": 123,
            "id": 2,
            "x_center": 0.749,
            "y_center": 0.43,
            "width": 0.054,
            "height": 0.01,
            "conf": 0.597,
        },
        {
            "frame": 124,
            "id": 2,
            "x_center": 0.755,
            "y_center": 0.43,
            "width": 0.049,
            "height": 0.009,
            "conf": 0.294,
        },
        {
            "frame": 125,
            "id": 2,
            "x_center": 0.763,
            "y_center": 0.43,
            "width": 0.043,
            "height": 0.009,
            "conf": 0.279,
        },
    ]


@pytest.fixture
def no_cross_tracks():
    """Fixture for sample data where no fish cross the line."""
    return [
        {
            "frame": 1,
            "id": 1,
            "x_center": 0.1,
            "y_center": 0.3,
            "width": 0.05,
            "height": 0.05,
            "conf": 0.9,
        },
        {
            "frame": 2,
            "id": 1,
            "x_center": 0.1,
            "y_center": 0.3,
            "width": 0.05,
            "height": 0.05,
            "conf": 0.9,
        },
    ]


@pytest.fixture
def no_tracks_null_dict():
    """Fixture for sample data where there are no tracks."""
    return [
        {},
        {
            "frame": None,
            "id": None,
            "x_center": None,
            "y_center": None,
            "width": None,
            "height": None,
            "conf": None,
        },
    ]


@pytest.fixture
def no_tracks_empty_dict():
    """Fixture for sample data where there are no tracks."""
    return [{}]


@pytest.fixture
def milling():
    """Fixture for milling fish."""
    return [
        {
            "frame": 93,
            "id": 2,
            "x_center": 0.42,
            "y_center": 0.436,
            "width": 0.08,
            "height": 0.01,
            "conf": 0.711,
        },
        {
            "frame": 94,
            "id": 2,
            "x_center": 0.42,
            "y_center": 0.436,
            "width": 0.08,
            "height": 0.01,
            "conf": 0.711,
        },
    ]


@pytest.fixture
def tracks_crossing_right_to_left():
    """Fixture for sample track data crossing from right-to-left."""
    return [
        {
            "frame": 331,
            "id": 9,
            "x_center": 0.607,
            "y_center": 0.772,
            "width": 0.021,
            "height": 0.007,
            "conf": 0.452,
        },
        {
            "frame": 332,
            "id": 9,
            "x_center": 0.608,
            "y_center": 0.772,
            "width": 0.021,
            "height": 0.007,
            "conf": 0.515,
        },
        {
            "frame": 333,
            "id": 9,
            "x_center": 0.604,
            "y_center": 0.772,
            "width": 0.023,
            "height": 0.007,
            "conf": 0.595,
        },
        {
            "frame": 334,
            "id": 9,
            "x_center": 0.602,
            "y_center": 0.773,
            "width": 0.025,
            "height": 0.007,
            "conf": 0.608,
        },
        {
            "frame": 335,
            "id": 9,
            "x_center": 0.598,
            "y_center": 0.773,
            "width": 0.028,
            "height": 0.008,
            "conf": 0.595,
        },
        {
            "frame": 336,
            "id": 9,
            "x_center": 0.595,
            "y_center": 0.774,
            "width": 0.031,
            "height": 0.008,
            "conf": 0.58,
        },
        {
            "frame": 337,
            "id": 9,
            "x_center": 0.59,
            "y_center": 0.774,
            "width": 0.035,
            "height": 0.008,
            "conf": 0.6,
        },
        {
            "frame": 338,
            "id": 9,
            "x_center": 0.586,
            "y_center": 0.774,
            "width": 0.038,
            "height": 0.008,
            "conf": 0.625,
        },
        {
            "frame": 339,
            "id": 9,
            "x_center": 0.582,
            "y_center": 0.773,
            "width": 0.042,
            "height": 0.009,
            "conf": 0.65,
        },
        {
            "frame": 340,
            "id": 9,
            "x_center": 0.578,
            "y_center": 0.773,
            "width": 0.044,
            "height": 0.009,
            "conf": 0.688,
        },
        {
            "frame": 341,
            "id": 9,
            "x_center": 0.575,
            "y_center": 0.773,
            "width": 0.048,
            "height": 0.009,
            "conf": 0.708,
        },
        {
            "frame": 342,
            "id": 9,
            "x_center": 0.569,
            "y_center": 0.772,
            "width": 0.052,
            "height": 0.009,
            "conf": 0.56,
        },
        {
            "frame": 343,
            "id": 9,
            "x_center": 0.565,
            "y_center": 0.772,
            "width": 0.056,
            "height": 0.009,
            "conf": 0.579,
        },
        {
            "frame": 344,
            "id": 9,
            "x_center": 0.562,
            "y_center": 0.771,
            "width": 0.059,
            "height": 0.009,
            "conf": 0.58,
        },
        {
            "frame": 345,
            "id": 9,
            "x_center": 0.556,
            "y_center": 0.771,
            "width": 0.063,
            "height": 0.009,
            "conf": 0.634,
        },
        {
            "frame": 346,
            "id": 9,
            "x_center": 0.548,
            "y_center": 0.77,
            "width": 0.065,
            "height": 0.01,
            "conf": 0.696,
        },
        {
            "frame": 347,
            "id": 9,
            "x_center": 0.546,
            "y_center": 0.769,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.737,
        },
        {
            "frame": 348,
            "id": 9,
            "x_center": 0.546,
            "y_center": 0.768,
            "width": 0.07,
            "height": 0.011,
            "conf": 0.705,
        },
        {
            "frame": 349,
            "id": 9,
            "x_center": 0.545,
            "y_center": 0.767,
            "width": 0.072,
            "height": 0.012,
            "conf": 0.643,
        },
        {
            "frame": 350,
            "id": 9,
            "x_center": 0.536,
            "y_center": 0.765,
            "width": 0.071,
            "height": 0.012,
            "conf": 0.573,
        },
        {
            "frame": 351,
            "id": 9,
            "x_center": 0.531,
            "y_center": 0.763,
            "width": 0.072,
            "height": 0.012,
            "conf": 0.613,
        },
        {
            "frame": 352,
            "id": 9,
            "x_center": 0.531,
            "y_center": 0.761,
            "width": 0.072,
            "height": 0.012,
            "conf": 0.64,
        },
        {
            "frame": 353,
            "id": 9,
            "x_center": 0.527,
            "y_center": 0.76,
            "width": 0.071,
            "height": 0.012,
            "conf": 0.724,
        },
        {
            "frame": 354,
            "id": 9,
            "x_center": 0.526,
            "y_center": 0.76,
            "width": 0.07,
            "height": 0.012,
            "conf": 0.694,
        },
        {
            "frame": 355,
            "id": 9,
            "x_center": 0.524,
            "y_center": 0.759,
            "width": 0.07,
            "height": 0.012,
            "conf": 0.702,
        },
        {
            "frame": 356,
            "id": 9,
            "x_center": 0.519,
            "y_center": 0.758,
            "width": 0.071,
            "height": 0.011,
            "conf": 0.691,
        },
        {
            "frame": 357,
            "id": 9,
            "x_center": 0.515,
            "y_center": 0.757,
            "width": 0.071,
            "height": 0.011,
            "conf": 0.681,
        },
        {
            "frame": 358,
            "id": 9,
            "x_center": 0.514,
            "y_center": 0.755,
            "width": 0.072,
            "height": 0.01,
            "conf": 0.631,
        },
        {
            "frame": 359,
            "id": 9,
            "x_center": 0.51,
            "y_center": 0.755,
            "width": 0.072,
            "height": 0.01,
            "conf": 0.667,
        },
        {
            "frame": 360,
            "id": 9,
            "x_center": 0.505,
            "y_center": 0.755,
            "width": 0.071,
            "height": 0.01,
            "conf": 0.676,
        },
        {
            "frame": 361,
            "id": 9,
            "x_center": 0.499,
            "y_center": 0.755,
            "width": 0.071,
            "height": 0.009,
            "conf": 0.687,
        },
        {
            "frame": 362,
            "id": 9,
            "x_center": 0.493,
            "y_center": 0.755,
            "width": 0.068,
            "height": 0.01,
            "conf": 0.715,
        },
        {
            "frame": 363,
            "id": 9,
            "x_center": 0.49,
            "y_center": 0.754,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.755,
        },
        {
            "frame": 364,
            "id": 9,
            "x_center": 0.487,
            "y_center": 0.754,
            "width": 0.068,
            "height": 0.01,
            "conf": 0.633,
        },
        {
            "frame": 365,
            "id": 9,
            "x_center": 0.478,
            "y_center": 0.755,
            "width": 0.07,
            "height": 0.01,
            "conf": 0.677,
        },
        {
            "frame": 366,
            "id": 9,
            "x_center": 0.469,
            "y_center": 0.756,
            "width": 0.071,
            "height": 0.01,
            "conf": 0.701,
        },
        {
            "frame": 367,
            "id": 9,
            "x_center": 0.461,
            "y_center": 0.756,
            "width": 0.07,
            "height": 0.01,
            "conf": 0.722,
        },
        {
            "frame": 368,
            "id": 9,
            "x_center": 0.457,
            "y_center": 0.756,
            "width": 0.069,
            "height": 0.01,
            "conf": 0.746,
        },
        {
            "frame": 369,
            "id": 9,
            "x_center": 0.453,
            "y_center": 0.756,
            "width": 0.07,
            "height": 0.01,
            "conf": 0.801,
        },
        {
            "frame": 370,
            "id": 9,
            "x_center": 0.448,
            "y_center": 0.757,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.651,
        },
        {
            "frame": 371,
            "id": 9,
            "x_center": 0.441,
            "y_center": 0.758,
            "width": 0.066,
            "height": 0.01,
            "conf": 0.694,
        },
        {
            "frame": 372,
            "id": 9,
            "x_center": 0.436,
            "y_center": 0.759,
            "width": 0.064,
            "height": 0.01,
            "conf": 0.705,
        },
        {
            "frame": 373,
            "id": 9,
            "x_center": 0.434,
            "y_center": 0.759,
            "width": 0.064,
            "height": 0.01,
            "conf": 0.725,
        },
        {
            "frame": 374,
            "id": 9,
            "x_center": 0.431,
            "y_center": 0.76,
            "width": 0.065,
            "height": 0.01,
            "conf": 0.682,
        },
        {
            "frame": 375,
            "id": 9,
            "x_center": 0.429,
            "y_center": 0.76,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.71,
        },
        {
            "frame": 376,
            "id": 9,
            "x_center": 0.424,
            "y_center": 0.76,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.725,
        },
        {
            "frame": 377,
            "id": 9,
            "x_center": 0.419,
            "y_center": 0.76,
            "width": 0.067,
            "height": 0.01,
            "conf": 0.719,
        },
        {
            "frame": 378,
            "id": 9,
            "x_center": 0.414,
            "y_center": 0.761,
            "width": 0.068,
            "height": 0.009,
            "conf": 0.705,
        },
        {
            "frame": 379,
            "id": 9,
            "x_center": 0.407,
            "y_center": 0.761,
            "width": 0.069,
            "height": 0.009,
            "conf": 0.697,
        },
        {
            "frame": 380,
            "id": 9,
            "x_center": 0.4,
            "y_center": 0.761,
            "width": 0.069,
            "height": 0.009,
            "conf": 0.698,
        },
        {
            "frame": 381,
            "id": 9,
            "x_center": 0.395,
            "y_center": 0.761,
            "width": 0.071,
            "height": 0.009,
            "conf": 0.686,
        },
        {
            "frame": 382,
            "id": 9,
            "x_center": 0.39,
            "y_center": 0.76,
            "width": 0.073,
            "height": 0.009,
            "conf": 0.72,
        },
        {
            "frame": 383,
            "id": 9,
            "x_center": 0.386,
            "y_center": 0.76,
            "width": 0.074,
            "height": 0.01,
            "conf": 0.71,
        },
        {
            "frame": 384,
            "id": 9,
            "x_center": 0.387,
            "y_center": 0.759,
            "width": 0.074,
            "height": 0.01,
            "conf": 0.715,
        },
        {
            "frame": 385,
            "id": 9,
            "x_center": 0.385,
            "y_center": 0.759,
            "width": 0.073,
            "height": 0.01,
            "conf": 0.722,
        },
        {
            "frame": 386,
            "id": 9,
            "x_center": 0.38,
            "y_center": 0.758,
            "width": 0.072,
            "height": 0.011,
            "conf": 0.764,
        },
        {
            "frame": 387,
            "id": 9,
            "x_center": 0.375,
            "y_center": 0.756,
            "width": 0.072,
            "height": 0.012,
            "conf": 0.727,
        },
        {
            "frame": 388,
            "id": 9,
            "x_center": 0.37,
            "y_center": 0.755,
            "width": 0.073,
            "height": 0.013,
            "conf": 0.732,
        },
        {
            "frame": 389,
            "id": 9,
            "x_center": 0.368,
            "y_center": 0.753,
            "width": 0.072,
            "height": 0.014,
            "conf": 0.656,
        },
        {
            "frame": 390,
            "id": 9,
            "x_center": 0.366,
            "y_center": 0.752,
            "width": 0.067,
            "height": 0.013,
            "conf": 0.653,
        },
        {
            "frame": 391,
            "id": 9,
            "x_center": 0.369,
            "y_center": 0.752,
            "width": 0.065,
            "height": 0.012,
            "conf": 0.595,
        },
        {
            "frame": 392,
            "id": 9,
            "x_center": 0.37,
            "y_center": 0.753,
            "width": 0.063,
            "height": 0.011,
            "conf": 0.512,
        },
        {
            "frame": 393,
            "id": 9,
            "x_center": 0.367,
            "y_center": 0.752,
            "width": 0.061,
            "height": 0.011,
            "conf": 0.564,
        },
        {
            "frame": 394,
            "id": 9,
            "x_center": 0.371,
            "y_center": 0.754,
            "width": 0.058,
            "height": 0.01,
            "conf": 0.358,
        },
    ]
