import os
from pathlib import Path

import pytest

ARIS_FILE = os.path.join(os.path.dirname(__file__), "data", "sample.aris")
DDF_FILE = os.path.join(os.path.dirname(__file__), "data", "sample.ddf")
CORRUPTED_FILE = os.path.join(os.path.dirname(__file__), "data", "corrupted.aris")
SHORTENED_DDF_FILE = os.path.join(
    os.path.dirname(__file__), "data", "shortened_clip.ddf"
)
INVALID_FRAME_INDICES = os.path.join(
    os.path.dirname(__file__), "data", "invalid_frame_indices.aris"
)


@pytest.fixture(scope="session")
def beam_widths_path():
    """Fixture to get the path to the beam_widths directory."""
    project_root = Path(__file__).parent.parent  # Get the root of the fisheye/ project
    beam_widths_dir = (
        project_root / "fisheye" / "beam_widths"
    )  # Navigate to beam_widths
    return beam_widths_dir


@pytest.fixture
def sample_tracks():
    """Fixture for sample track data."""

    return [
        {
            "frame": 48,
            "id": 2,
            "bb_left": 0.201,
            "bb_top": 0.432,
            "bb_width": 0.028,
            "bb_height": 0.008,
            "conf": 0.444,
        },
        {
            "frame": 49,
            "id": 2,
            "bb_left": 0.202,
            "bb_top": 0.432,
            "bb_width": 0.032,
            "bb_height": 0.008,
            "conf": 0.548,
        },
        {
            "frame": 50,
            "id": 2,
            "bb_left": 0.201,
            "bb_top": 0.432,
            "bb_width": 0.035,
            "bb_height": 0.009,
            "conf": 0.611,
        },
        {
            "frame": 51,
            "id": 2,
            "bb_left": 0.199,
            "bb_top": 0.43,
            "bb_width": 0.042,
            "bb_height": 0.011,
            "conf": 0.566,
        },
        {
            "frame": 52,
            "id": 2,
            "bb_left": 0.201,
            "bb_top": 0.43,
            "bb_width": 0.048,
            "bb_height": 0.012,
            "conf": 0.516,
        },
        {
            "frame": 53,
            "id": 2,
            "bb_left": 0.203,
            "bb_top": 0.43,
            "bb_width": 0.051,
            "bb_height": 0.014,
            "conf": 0.321,
        },
        {
            "frame": 54,
            "id": 2,
            "bb_left": 0.206,
            "bb_top": 0.43,
            "bb_width": 0.053,
            "bb_height": 0.014,
            "conf": 0.217,
        },
        {
            "frame": 55,
            "id": 2,
            "bb_left": 0.203,
            "bb_top": 0.428,
            "bb_width": 0.057,
            "bb_height": 0.015,
            "conf": 0.313,
        },
        {
            "frame": 56,
            "id": 2,
            "bb_left": 0.219,
            "bb_top": 0.432,
            "bb_width": 0.062,
            "bb_height": 0.016,
            "conf": 0.195,
        },
        {
            "frame": 57,
            "id": 2,
            "bb_left": 0.235,
            "bb_top": 0.434,
            "bb_width": 0.06,
            "bb_height": 0.014,
            "conf": 0.312,
        },
        {
            "frame": 60,
            "id": 2,
            "bb_left": 0.256,
            "bb_top": 0.438,
            "bb_width": 0.059,
            "bb_height": 0.013,
            "conf": 0.46,
        },
        {
            "frame": 61,
            "id": 2,
            "bb_left": 0.263,
            "bb_top": 0.439,
            "bb_width": 0.056,
            "bb_height": 0.012,
            "conf": 0.367,
        },
        {
            "frame": 62,
            "id": 2,
            "bb_left": 0.266,
            "bb_top": 0.437,
            "bb_width": 0.059,
            "bb_height": 0.014,
            "conf": 0.406,
        },
        {
            "frame": 63,
            "id": 2,
            "bb_left": 0.276,
            "bb_top": 0.439,
            "bb_width": 0.057,
            "bb_height": 0.013,
            "conf": 0.307,
        },
        {
            "frame": 64,
            "id": 2,
            "bb_left": 0.29,
            "bb_top": 0.442,
            "bb_width": 0.059,
            "bb_height": 0.011,
            "conf": 0.575,
        },
        {
            "frame": 65,
            "id": 2,
            "bb_left": 0.295,
            "bb_top": 0.443,
            "bb_width": 0.058,
            "bb_height": 0.011,
            "conf": 0.507,
        },
        {
            "frame": 66,
            "id": 2,
            "bb_left": 0.299,
            "bb_top": 0.443,
            "bb_width": 0.059,
            "bb_height": 0.01,
            "conf": 0.623,
        },
        {
            "frame": 67,
            "id": 2,
            "bb_left": 0.302,
            "bb_top": 0.443,
            "bb_width": 0.06,
            "bb_height": 0.01,
            "conf": 0.558,
        },
        {
            "frame": 68,
            "id": 2,
            "bb_left": 0.309,
            "bb_top": 0.443,
            "bb_width": 0.062,
            "bb_height": 0.009,
            "conf": 0.613,
        },
        {
            "frame": 69,
            "id": 2,
            "bb_left": 0.313,
            "bb_top": 0.443,
            "bb_width": 0.065,
            "bb_height": 0.009,
            "conf": 0.555,
        },
        {
            "frame": 70,
            "id": 2,
            "bb_left": 0.315,
            "bb_top": 0.443,
            "bb_width": 0.069,
            "bb_height": 0.01,
            "conf": 0.636,
        },
        {
            "frame": 71,
            "id": 2,
            "bb_left": 0.315,
            "bb_top": 0.442,
            "bb_width": 0.075,
            "bb_height": 0.01,
            "conf": 0.591,
        },
        {
            "frame": 72,
            "id": 2,
            "bb_left": 0.322,
            "bb_top": 0.442,
            "bb_width": 0.077,
            "bb_height": 0.01,
            "conf": 0.6,
        },
        {
            "frame": 73,
            "id": 2,
            "bb_left": 0.325,
            "bb_top": 0.442,
            "bb_width": 0.081,
            "bb_height": 0.01,
            "conf": 0.673,
        },
        {
            "frame": 74,
            "id": 2,
            "bb_left": 0.346,
            "bb_top": 0.443,
            "bb_width": 0.078,
            "bb_height": 0.01,
            "conf": 0.499,
        },
        {
            "frame": 75,
            "id": 2,
            "bb_left": 0.347,
            "bb_top": 0.442,
            "bb_width": 0.081,
            "bb_height": 0.01,
            "conf": 0.65,
        },
        {
            "frame": 76,
            "id": 2,
            "bb_left": 0.357,
            "bb_top": 0.441,
            "bb_width": 0.079,
            "bb_height": 0.01,
            "conf": 0.569,
        },
        {
            "frame": 77,
            "id": 2,
            "bb_left": 0.362,
            "bb_top": 0.441,
            "bb_width": 0.08,
            "bb_height": 0.01,
            "conf": 0.507,
        },
        {
            "frame": 78,
            "id": 2,
            "bb_left": 0.376,
            "bb_top": 0.442,
            "bb_width": 0.074,
            "bb_height": 0.009,
            "conf": 0.616,
        },
        {
            "frame": 79,
            "id": 2,
            "bb_left": 0.383,
            "bb_top": 0.441,
            "bb_width": 0.074,
            "bb_height": 0.009,
            "conf": 0.623,
        },
        {
            "frame": 80,
            "id": 2,
            "bb_left": 0.39,
            "bb_top": 0.441,
            "bb_width": 0.077,
            "bb_height": 0.009,
            "conf": 0.643,
        },
        {
            "frame": 81,
            "id": 2,
            "bb_left": 0.394,
            "bb_top": 0.44,
            "bb_width": 0.078,
            "bb_height": 0.009,
            "conf": 0.631,
        },
        {
            "frame": 82,
            "id": 2,
            "bb_left": 0.4,
            "bb_top": 0.44,
            "bb_width": 0.08,
            "bb_height": 0.009,
            "conf": 0.656,
        },
        {
            "frame": 83,
            "id": 2,
            "bb_left": 0.408,
            "bb_top": 0.44,
            "bb_width": 0.081,
            "bb_height": 0.009,
            "conf": 0.647,
        },
        {
            "frame": 84,
            "id": 2,
            "bb_left": 0.414,
            "bb_top": 0.439,
            "bb_width": 0.085,
            "bb_height": 0.01,
            "conf": 0.686,
        },
        {
            "frame": 85,
            "id": 2,
            "bb_left": 0.422,
            "bb_top": 0.438,
            "bb_width": 0.086,
            "bb_height": 0.01,
            "conf": 0.689,
        },
        {
            "frame": 86,
            "id": 2,
            "bb_left": 0.442,
            "bb_top": 0.438,
            "bb_width": 0.084,
            "bb_height": 0.01,
            "conf": 0.596,
        },
        {
            "frame": 87,
            "id": 2,
            "bb_left": 0.45,
            "bb_top": 0.438,
            "bb_width": 0.083,
            "bb_height": 0.01,
            "conf": 0.628,
        },
        {
            "frame": 88,
            "id": 2,
            "bb_left": 0.457,
            "bb_top": 0.437,
            "bb_width": 0.08,
            "bb_height": 0.009,
            "conf": 0.65,
        },
        {
            "frame": 89,
            "id": 2,
            "bb_left": 0.467,
            "bb_top": 0.437,
            "bb_width": 0.079,
            "bb_height": 0.009,
            "conf": 0.683,
        },
        {
            "frame": 90,
            "id": 2,
            "bb_left": 0.478,
            "bb_top": 0.437,
            "bb_width": 0.078,
            "bb_height": 0.009,
            "conf": 0.704,
        },
        {
            "frame": 91,
            "id": 2,
            "bb_left": 0.485,
            "bb_top": 0.437,
            "bb_width": 0.079,
            "bb_height": 0.01,
            "conf": 0.715,
        },
        {
            "frame": 92,
            "id": 2,
            "bb_left": 0.493,
            "bb_top": 0.436,
            "bb_width": 0.08,
            "bb_height": 0.01,
            "conf": 0.701,
        },
        {
            "frame": 93,
            "id": 2,
            "bb_left": 0.503,
            "bb_top": 0.436,
            "bb_width": 0.08,
            "bb_height": 0.01,
            "conf": 0.711,
        },
        {
            "frame": 94,
            "id": 2,
            "bb_left": 0.519,
            "bb_top": 0.436,
            "bb_width": 0.081,
            "bb_height": 0.01,
            "conf": 0.62,
        },
        {
            "frame": 95,
            "id": 2,
            "bb_left": 0.527,
            "bb_top": 0.436,
            "bb_width": 0.078,
            "bb_height": 0.01,
            "conf": 0.618,
        },
        {
            "frame": 96,
            "id": 2,
            "bb_left": 0.539,
            "bb_top": 0.436,
            "bb_width": 0.079,
            "bb_height": 0.01,
            "conf": 0.624,
        },
        {
            "frame": 97,
            "id": 2,
            "bb_left": 0.548,
            "bb_top": 0.436,
            "bb_width": 0.077,
            "bb_height": 0.009,
            "conf": 0.582,
        },
        {
            "frame": 98,
            "id": 2,
            "bb_left": 0.551,
            "bb_top": 0.436,
            "bb_width": 0.077,
            "bb_height": 0.009,
            "conf": 0.591,
        },
        {
            "frame": 99,
            "id": 2,
            "bb_left": 0.557,
            "bb_top": 0.435,
            "bb_width": 0.078,
            "bb_height": 0.009,
            "conf": 0.445,
        },
        {
            "frame": 100,
            "id": 2,
            "bb_left": 0.565,
            "bb_top": 0.435,
            "bb_width": 0.076,
            "bb_height": 0.01,
            "conf": 0.532,
        },
        {
            "frame": 101,
            "id": 2,
            "bb_left": 0.578,
            "bb_top": 0.435,
            "bb_width": 0.076,
            "bb_height": 0.01,
            "conf": 0.566,
        },
        {
            "frame": 102,
            "id": 2,
            "bb_left": 0.589,
            "bb_top": 0.434,
            "bb_width": 0.079,
            "bb_height": 0.01,
            "conf": 0.61,
        },
        {
            "frame": 103,
            "id": 2,
            "bb_left": 0.597,
            "bb_top": 0.434,
            "bb_width": 0.081,
            "bb_height": 0.01,
            "conf": 0.638,
        },
        {
            "frame": 104,
            "id": 2,
            "bb_left": 0.605,
            "bb_top": 0.434,
            "bb_width": 0.08,
            "bb_height": 0.01,
            "conf": 0.572,
        },
        {
            "frame": 105,
            "id": 2,
            "bb_left": 0.611,
            "bb_top": 0.434,
            "bb_width": 0.082,
            "bb_height": 0.01,
            "conf": 0.556,
        },
        {
            "frame": 106,
            "id": 2,
            "bb_left": 0.616,
            "bb_top": 0.434,
            "bb_width": 0.082,
            "bb_height": 0.01,
            "conf": 0.551,
        },
        {
            "frame": 107,
            "id": 2,
            "bb_left": 0.632,
            "bb_top": 0.434,
            "bb_width": 0.079,
            "bb_height": 0.01,
            "conf": 0.57,
        },
        {
            "frame": 108,
            "id": 2,
            "bb_left": 0.639,
            "bb_top": 0.434,
            "bb_width": 0.078,
            "bb_height": 0.01,
            "conf": 0.517,
        },
        {
            "frame": 109,
            "id": 2,
            "bb_left": 0.649,
            "bb_top": 0.434,
            "bb_width": 0.078,
            "bb_height": 0.01,
            "conf": 0.633,
        },
        {
            "frame": 110,
            "id": 2,
            "bb_left": 0.656,
            "bb_top": 0.434,
            "bb_width": 0.077,
            "bb_height": 0.01,
            "conf": 0.633,
        },
        {
            "frame": 111,
            "id": 2,
            "bb_left": 0.658,
            "bb_top": 0.433,
            "bb_width": 0.077,
            "bb_height": 0.01,
            "conf": 0.63,
        },
        {
            "frame": 112,
            "id": 2,
            "bb_left": 0.661,
            "bb_top": 0.433,
            "bb_width": 0.075,
            "bb_height": 0.01,
            "conf": 0.514,
        },
        {
            "frame": 113,
            "id": 2,
            "bb_left": 0.676,
            "bb_top": 0.433,
            "bb_width": 0.073,
            "bb_height": 0.01,
            "conf": 0.482,
        },
        {
            "frame": 114,
            "id": 2,
            "bb_left": 0.686,
            "bb_top": 0.433,
            "bb_width": 0.073,
            "bb_height": 0.01,
            "conf": 0.27,
        },
        {
            "frame": 115,
            "id": 2,
            "bb_left": 0.699,
            "bb_top": 0.434,
            "bb_width": 0.074,
            "bb_height": 0.01,
            "conf": 0.434,
        },
        {
            "frame": 116,
            "id": 2,
            "bb_left": 0.706,
            "bb_top": 0.433,
            "bb_width": 0.074,
            "bb_height": 0.01,
            "conf": 0.434,
        },
        {
            "frame": 117,
            "id": 2,
            "bb_left": 0.719,
            "bb_top": 0.433,
            "bb_width": 0.073,
            "bb_height": 0.01,
            "conf": 0.515,
        },
        {
            "frame": 118,
            "id": 2,
            "bb_left": 0.728,
            "bb_top": 0.433,
            "bb_width": 0.07,
            "bb_height": 0.01,
            "conf": 0.591,
        },
        {
            "frame": 119,
            "id": 2,
            "bb_left": 0.732,
            "bb_top": 0.432,
            "bb_width": 0.067,
            "bb_height": 0.01,
            "conf": 0.659,
        },
        {
            "frame": 120,
            "id": 2,
            "bb_left": 0.735,
            "bb_top": 0.431,
            "bb_width": 0.064,
            "bb_height": 0.01,
            "conf": 0.677,
        },
        {
            "frame": 121,
            "id": 2,
            "bb_left": 0.738,
            "bb_top": 0.43,
            "bb_width": 0.062,
            "bb_height": 0.01,
            "conf": 0.686,
        },
        {
            "frame": 122,
            "id": 2,
            "bb_left": 0.742,
            "bb_top": 0.43,
            "bb_width": 0.059,
            "bb_height": 0.01,
            "conf": 0.616,
        },
        {
            "frame": 123,
            "id": 2,
            "bb_left": 0.749,
            "bb_top": 0.43,
            "bb_width": 0.054,
            "bb_height": 0.01,
            "conf": 0.597,
        },
        {
            "frame": 124,
            "id": 2,
            "bb_left": 0.755,
            "bb_top": 0.43,
            "bb_width": 0.049,
            "bb_height": 0.009,
            "conf": 0.294,
        },
        {
            "frame": 125,
            "id": 2,
            "bb_left": 0.763,
            "bb_top": 0.43,
            "bb_width": 0.043,
            "bb_height": 0.009,
            "conf": 0.279,
        },
    ]


@pytest.fixture
def no_cross_tracks():
    """Fixture for sample data where no fish cross the line."""
    return [
        {
            "frame": 1,
            "id": 1,
            "bb_left": 0.1,
            "bb_top": 0.3,
            "bb_width": 0.05,
            "bb_height": 0.05,
            "conf": 0.9,
        },
        {
            "frame": 2,
            "id": 1,
            "bb_left": 0.1,
            "bb_top": 0.3,
            "bb_width": 0.05,
            "bb_height": 0.05,
            "conf": 0.9,
        },
    ]


@pytest.fixture
def no_tracks():
    """Fixture for sample data where there are no tracks."""
    return [
        {},
        {
            "frame": None,
            "id": None,
            "bb_left": None,
            "bb_top": None,
            "bb_width": None,
            "bb_height": None,
            "conf": None,
        },
    ]
