# Dockerfile.mac
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy poetry files first for caching
COPY pyproject.toml poetry.lock README.md ./

# Copy the rest of the codebase
COPY . .

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ~/.local/bin/poetry config virtualenvs.create false && \
    ~/.local/bin/poetry install --no-interaction --no-ansi

# Default: start shell (can override with `make run`)
CMD ["/bin/bash"]
