# Dockerfile.jetson

# Use NVIDIA’s PyTorch image with CUDA (already has torch, torchvision, etc.)
FROM nvcr.io/nvidia/l4t-base:r35.4.1

# Set environment variables for non-interactive installs
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    python3-venv \
    curl \
    git \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    llvm \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev \
    libpng-dev \
    Libjpeg-dev
    && rm -rf /var/lib/apt/lists/*

# Ensure `python` and `pip` point to Python 3
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

# Set working directory
WORKDIR /app

# Copy poetry files first for caching
COPY pyproject.toml poetry.lock README.md ./

# Copy the rest of the codebase
COPY . .

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ~/.local/bin/poetry config virtualenvs.create false

# Add Poetry to PATh
ENV PATH="/root/.local/bin:$PATH"

# Install only core dependencies needed for NVIDIA Jetson AGX Orin
RUN poetry install --no-interaction --no-ansi --without dev -- without test --without mac

# Install Jetson-compatible PyTorch wheel
RUN pip install https://developer.download.nvidia.com/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl

# Install torchvision
RUN pip install torchvision-0.15.1-*.whl

RUN chmod +x run.sh

# Make sure all entrypoints and scripts use bash
SHELL ["/bin/bash", "-c"]