dataset:
  batch_size: 1
  workers: 0
  use_multithreading: false
  max_workers: 2  # For multithreading

model:
  type: yolov5
  weights: weights/cfc_detect_yolov5s_v0.pt
  device: cpu

inference:
  use_multithreading: false
  max_workers: 2  # For multithreading
