dataset:
  batch_size: 32
  workers: 10  # For dataloader
  use_multithreading: false
  max_workers: 2  # For multithreading
  use_blur: true

model:
  type: yolov5
  weights: weights/cfc_detect_yolov5m_v0.pt
  device: cuda:0

inference:
  use_multithreading: false
  max_workers: 2  # For multithreading
  apply_nms_batchwise: true
  apply_length_estimates_batchwise: false
  length_config:
    type: unet
    weights: null