dataset:
  batch_size: 4
  workers: 0 # For dataloader
  use_multithreading: false
  use_blur: true
  max_workers: 2 # For multithreading

model:
  type: yolov5
  weights: weights/cfc_detect_yolov5s_v1.pt
  device: cuda:0

inference:
  use_multithreading: false
  apply_nms_batchwise: true
  max_workers: 2 # For multithreading
