# Default values for FC TXT export
FC_DEFAULT_LENGTH_CM = 0.0  # "L(cm)"
FC_DEFAULT_DR_CM = 0.0  # "dR(cm)"
FC_DEFAULT_L_OVER_R = 0.0  # "L/dR"
FC_DEFAULT_ASPECT = 0.0  # "Aspect"
FC_DEFAULT_TIME = "00:00:00"  # "Time"
FC_DEFAULT_LATITUDE = "N 00 d  0.00000 m"
FC_DEFAULT_LONGITUDE = "E 000 d  0.00000 m"
FC_DEFAULT_PAN = 0.0  # "Pan"
FC_DEFAULT_TILT = 0.0  # "Tilt"
FC_DEFAULT_ROLL = 0.0  # "Roll"
FC_DEFAULT_SPECIES = "Unknown"  # "Species"
FC_DEFAULT_MOTION = "Running <->"  # "Motion"
FC_DEFAULT_QUALITY = 5  # "Q"
FC_DEFAULT_REPEAT_COUNT = 1  # "N"
FC_DEFAULT_COMMENT = ""  # "Comment"
